# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_auto_20170424_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='APP/ACC', max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
