# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_auto_20170424_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('APP/ACC', 'Apparel/Accesory'), ('ENT', 'Entertainment'), ('F/B', 'Food/Beverage'), ('SC/C', 'Skin care/Cosmetics'), ('C/M', 'Computer/Mobile'), ('B/N', 'Books/Newspapers')], default='APP/ACC', max_length=30),
        ),
    ]
