# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_auto_20170424_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
