# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0013_remove_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
