# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0016_auto_20170512_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
