# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0017_auto_20170512_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
